### ISSUE TITLE
hexo添加gitalk,gitment社会化评论系统 | ManfredHu胡文峰的个人博客

### ISSUE THREAD

**Issue by ManfredHu** [ManfredHu/manfredHu.github.io#3]
https://www.manfredhu.com/2018/11/05/37-gitalk-comment-system/ 

 社会化评论系统，类似留言板的功能，本来还想自己写一个的。Mongodb都下好了，然后看到了一个项目——gitalk。亲测hexo搭建的基于github page的页面可以使用。用到了github授权第三方登陆的方式，做的，项目地址在这里：https://github.com/gitalk/gitalk还有个叫gitment的，项目地址在这里：https://github.com/imsun/git

**Comment by feyond** [comment]
你的侧边栏很cool

**Comment by ManfredHu** [comment]
谢谢

**Comment by songguoguo927** [comment]
test

**Comment by whtiehack** [comment]
aaaaa

**Comment by Eajack** [comment]
求问，我网页是github.io的，不是com这类域名，也可以的吗？

**Comment by ManfredHu** [comment]
@Eajack 都可以的
